services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docktainer:
    image: ghcr.io/firstdarkdev/docktainer:latest
    #build: .
    container_name: "docktainer"
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./storage/html:/app/html
      - ./storage/ssl:/app/ssl
      - ./storage/webhook.log:/app/webhook.log